name: Deploy

on:
  push:
    tags:
      - firsttestpackage-*.*.*

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node, npm, and dependencies
        uses: ./.github/actions/install-dependencies

      - name: Publish packages from git
        run: echo "automatically deploy packages"
        shell: bash
