name: Publish

on:
  push:
    tags:
      - first-package-common-lib-*.*.*

jobs:
  test:
    name: Publish
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node, npm, and dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set auth credentials in .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Publish packages from git
        run: npx nx run first-package-common-lib:deploy
        shell: bash
