name: Release

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'The type of version bump to perform. Must be one of: major, minor, patch, premajor, preminor, prepatch, prerelease'
        required: true
      tag-to-search:
        description: 'Enter application name'
        required: true

permissions:
  contents: write

jobs:
  test:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node, npm, and dependencies
        uses: ./.github/actions/install-dependencies

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        shell: bash

      - name: Bump version of packages
        run: npx nx run ${{ inputs.tag-to-search }}:version
        shell: bash

      - name: Determine Old and Latest Commits
        id: commit-info
        run: |
          TAG_PREFIX="${{ inputs.tag-to-search }}"

          LATEST_TAG=$(git describe --tags --match "$TAG_PREFIX*" --abbrev=0)

          echo "::set-output name=new_tag::${LATEST_TAG}"

      - name: Push changes
        run: git push origin ${{ steps.commit-info.outputs.new_tag }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
