name: Version

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'The type of version bump to perform. Must be one of: major, minor, patch, premajor, preminor, prepatch, prerelease'
        required: true

permissions:
  contents: write

jobs:
  test:
    name: Version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install node, npm, and dependencies
        uses: ./.github/actions/install-dependencies

      - name: Configure git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
        shell: bash

      - name: Determine Old and Latest Commits
        id: commit-info
        run: |
          export LAST_TAG_COMMIT=$(git rev-list -n 1 $(git describe --abbrev=0 --tags))
          export HEAD_COMMIT=$(git rev-parse HEAD)
          echo $LAST_TAG_COMMIT
          echo $HEAD_COMMIT
          echo "::set-output name=old_commit::${LAST_TAG_COMMIT}"
          echo "::set-output name=head_commit::${HEAD_COMMIT}"

      - name: Bump version of packages
        run: npx nx affected --base="3fa1a5d3238006ed452e5a90082ace6180e51f6c" --head="1edbc14c882e2d9940023888374b2c591a2abd3c" --target=version
        shell: bash

      - name: Push changes to github
        run: git push origin --tags
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
